name: Current

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "github.event.label.name != 'dist_created' || !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Build Frontend
        run: npm install && npm run build

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Commit dist
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./dist --force
          git commit -m "Add vue dist"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: create dist
          title: Create dist directory [ci skip]
          branch: create_dist
          base: main
          labels: dist_created
          delete-branch: true
