name: Release

on:
  push:
    branches: [ release/** ]
  pull_request:
    branches: [ release/** ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: 1.16.0-rc1
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4      
    
    - name: Build Frontend
      run: npm install && npm run build     
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
